### ISSUE TITLE
Imcompatible with php7?

### ISSUE THREAD

**Issue by FabioZumbi12** [khacoder/testimonial-basics#2]
Hi,
I already using this plugin on my Wordpress, but on php5. Now my webhost is using php7 and i think is not compatible. This is the errors i get:

On widget:
`Array to string conversion in /home/sitez12/public_html/wp-content/plugins/testimonial-basics/includes/katb_functions.php on line 1060`

And this is how the testimonial page looks: http://prntscr.com/epaoym
If you want to look, visit my page: http://areaz12server.net.br/depoimentos/

Thanks and excellent plugin ^^

**Comment by khacoder** [comment]
Can you provide a screenshot for the widget settings?

**Comment by FabioZumbi12** [comment]
I already fixed, and opened a PR for you ;)
#3
